title: Alice Chen
logo: /assets/img/logo.png
description: <a href=https://github.com/alicewchen>GitHub</a> | <a href=https://www.linkedin.com/in/alicewchen/>LinkedIn</a>
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
